# GitHub Action Workflow to Deploy Node.js App to DockerHub
#
# Version      Date        Info
# 1.0          2022        First Version
# Made by Dmitry Solomatin
#---------------------------------------------------------------------
name: CI-CD to DockerHub
env:
  S3_BUCKET_NAME : "node.js-app"
  APPLICATION_NAME       : "nodejsapp"
  ENVIRONMENT_NAME       : "Nodejsapp-env"
  DEPLOY_PACKAGE_NAME       : "nodejsapp-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-north-1"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker_stage:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      - name: Check Out Repo 
        uses: actions/checkout@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          docker: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node-app-${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} 
